---------------------------------
--GP identified carers Swansea
---------------------------------
/* - Carers identified IN GP DATA FROM 2021-04-01 TO 2022-06-19
 * - Alive on event date
 * - Aged >= 18 on event date
 * - Known sex (1 or 2)
 * - Resides in NPT, Gwynedd, Denbighshire or Swansea on event date (Also accounts for known deprivation) - LSOA codes in SAILW1429V.LB_LSOA_LA_LOOKUP
 * - Resident in Wales for one year prior to event date
 * - Registered at a SAIL GP for one year prior to event date
 * - ALF_STS_CD 1, 4 or 39
 */

/* Cleaning steps
 * STEP 1  
 * 1. WDSD geography START_DT <= 2022-06-19 and END_DT >= 2021-04-01 (have an LSOA within study period)
 * 2. LSOA Swansea in lookup table 
 * 3. Link to WDSD demographics
 * 4. Sex 1 or 2
 * STEP 2
 * 5. Link to WLGP (inner join)
 *  -	ALF_STS_CD 1, 4 or 39
 *  -	Unpaid carer code with EVENT_DT during LSOA period
 * STEP 3
 * 6. Link to ADDE
 * 7. Drop rows with DEATH_DT before EVENT_DT
 * 8. Calculate age on EVENT_DT
 * 9. Drop rows under 18 on EVENT_DT
 * STEP 4
 * 10. Link to CLEAN_ADD_WALES
 * 11. drop those not resident in Wales for 1 year prior to EVENT_DT (GP EVENT_DT - 1 year >= WALES START_DATE) AND (GP EVENT_DT <= WALES END_DATE)
 * STEP 5 
 * 12. Link to WLGP SAIL practices
 * 13. Drop those not registered with a SAIL GP for 1 year prior to EVENT_DT
 * 14. Group by ALF, order by event date, add row number
 * 15. Remove all but first event_dt (where row number != 1)
 * LB_GPCARER_SWANSEA
 * 16. insert into final table
 * 17. Drop interim tables
 */

DROP TABLE SAILW1429V.LB_GPCARER_SWANSEA;

--STEP 1
CREATE TABLE SAILW1429V.LB_GPCARER_STEP1_SWANSEA (ALF_PE BIGINT,
START_DATE DATE,
END_DATE DATE,
LSOA2011_CD VARCHAR(10),
WIMD_2019_QUINTILE INTEGER,
LA_NAME VARCHAR(100),
RUC11 VARCHAR(47),
SEX INTEGER,
WOB DATE);

INSERT
	INTO
	SAILW1429V.LB_GPCARER_STEP1_SWANSEA
-- 3. Link to WDSD demographics
 SELECT
	DISTINCT B.*,
	R.RUC11,
	P.GNDR_CD AS SEX,
	P.WOB
FROM
	(
	-- 2. LSOA in lookup table as Swansea
	SELECT
		A.*,
		L.LA_NAME
	FROM
		(
		-- 1. WDSD geography START_DT <= 2022-06-30 and END_DT >= 2021-04-01 (have an LSOA within study period)
		SELECT
			ALF_PE,
			START_DATE,
			END_DATE,
			LSOA2011_CD,
			WIMD_2019_QUINTILE
		FROM
			SAIL1429V.WDSD_CLEAN_ADD_GEOG_CHAR_LSOA2011_20220704 G
		WHERE
			START_DATE <= '2022-06-19'
			AND END_DATE >= '2021-04-01' ) A
	INNER JOIN SAILW1429V.LB_LSOA_LA_LOOKUP L ON
		A.LSOA2011_CD = L.LSOA_CD
	WHERE
		LA_NAME = 'Swansea' ) B
LEFT JOIN
	SAILREFRV.RURAL_URBAN_CLASS_2011_OF_LLSOAREAS_IN_ENG_AND_WAL R ON 
	R.LSOA11CD = B.LSOA2011_CD
LEFT JOIN SAIL1429V.WDSD_AR_PERS_20220704 P ON
	B.ALF_PE = P.ALF_PE;

-- Adding step 4 here goes beyond counting capabilities of SAIL, so create table with output of steps 1-3.

-- 4. Sex 1 or 2
 DELETE
FROM
	SAILW1429V.LB_GPCARER_STEP1_SWANSEA
WHERE
	SEX NOT IN(1,
	2);


-- Remove those with no WOB
 DELETE
FROM
	SAILW1429V.LB_GPCARER_STEP1_SWANSEA
WHERE
	WOB IS NULL;


-- STEP 2
 CREATE TABLE SAILW1429V.LB_GPCARER_STEP2_SWANSEA (ALF_PE BIGINT,
START_DATE DATE,
END_DATE DATE,
LSOA2011_CD VARCHAR(10),
WIMD_2019_QUINTILE INTEGER,
LA_NAME VARCHAR(100),
RUC11 VARCHAR(47),
SEX INTEGER,
WOB DATE,
EVENT_DT DATE);

INSERT
	INTO
	SAILW1429V.LB_GPCARER_STEP2_SWANSEA
SELECT
	DISTINCT A.*,
	GP.EVENT_DT
FROM
	SAILW1429V.LB_GPCARER_STEP1_SWANSEA A
	--5. Link to WLGP (inner join)
INNER JOIN SAIL1429V.WLGP_GP_EVENT_CLEANSED_20220301 GP ON
	A.ALF_PE = GP.ALF_PE
	--  -	ALF_STS_CD 1, 4 or 39
	WHERE GP.ALF_STS_CD IN (1,
	4,
	39)
	--  -	Unpaid carer code with EVENT_DT during LSOA period
	AND GP.EVENT_CD IN(
	SELECT
		READ_CODE
	FROM
		(
		SELECT
			READ_CODE
		FROM
			SAILW1429V.LB_CARER_READ_CODES RC))
	-- GP carer code occurred whilst living at LSOA already selected
	AND GP.EVENT_DT BETWEEN A.START_DATE AND A.END_DATE
	-- GP carer code occurred within study period
	AND GP.EVENT_DT BETWEEN '2021-04-01' AND '2022-06-19';


-- STEP 3
 CREATE TABLE SAILW1429V.LB_GPCARER_STEP3_SWANSEA (ALF_PE BIGINT,
START_DATE DATE,
END_DATE DATE,
LSOA2011_CD VARCHAR(10),
WIMD_2019_QUINTILE INTEGER,
LA_NAME VARCHAR(100),
RUC11 VARCHAR(47),
SEX INTEGER,
WOB DATE,
EVENT_DT DATE,
DEATH_DT DATE);
-- 6. Link to ADDE
 INSERT
	INTO
	SAILW1429V.LB_GPCARER_STEP3_SWANSEA
SELECT
	A.*,
	D.DEATH_DT
FROM
	SAILW1429V.LB_GPCARER_STEP2_SWANSEA A
LEFT JOIN SAIL1429V.ADDE_DEATHS_20220701 D ON
	A.ALF_PE = D.ALF_PE
	
	-- There are no null ALF_STS_CDs in ADDE, so keeping rows where ADDE linked ALF_STS_CD is null is just those who don't have a death_dt
	WHERE (D.ALF_STS_CD IN(1,
	4,
	39)
	OR D.ALF_STS_CD IS NULL);


-- 7. Drop rows with DEATH_DT before EVENT_DT
 DELETE
FROM
	SAILW1429V.LB_GPCARER_STEP3_SWANSEA
WHERE
	DEATH_DT < EVENT_DT;


-- 8. Calculate age on EVENT_DT
 ALTER TABLE SAILW1429V.LB_GPCARER_STEP3_SWANSEA ADD COLUMN AGE INTEGER;

UPDATE
	SAILW1429V.LB_GPCARER_STEP3_SWANSEA
SET
	AGE = YEARS_BETWEEN(EVENT_DT,
	WOB);


-- 9. Drop rows under 18 on EVENT_DT
 DELETE
FROM
	SAILW1429V.LB_GPCARER_STEP3_SWANSEA
WHERE
	AGE < 18;


-- STEP 4
 CREATE TABLE SAILW1429V.LB_GPCARER_STEP4_SWANSEA (ALF_PE BIGINT,
LSOA_START_DATE DATE,
LSOA_END_DATE DATE,
LSOA2011_CD VARCHAR(10),
WIMD_2019_QUINTILE INTEGER,
LA_NAME VARCHAR(100),
RUC11 VARCHAR(47),
SEX INTEGER,
WOB DATE,
EVENT_DT DATE,
DEATH_DT DATE,
AGE INTEGER,
WELSH_START_DT DATE,
WELSH_END_DT DATE,
WELSH_ADDRESS INTEGER);
--10. Link to CLEAN_ADD_WALES
 INSERT
	INTO
	SAILW1429V.LB_GPCARER_STEP4_SWANSEA
SELECT
	DISTINCT A.*,
	W.START_DATE,
	W.END_DATE,
	W.WELSH_ADDRESS
FROM
	SAILW1429V.LB_GPCARER_STEP3_SWANSEA A
LEFT JOIN SAIL1429V.WDSD_CLEAN_ADD_WALES_20220704 W ON
	A.ALF_PE = W.ALF_PE
WHERE
	W.WELSH_ADDRESS = 1;


-- 11. drop those not resident in Wales for 1 year prior to EVENT_DT (GP EVENT_DT - 1 year >= WALES START_DATE) AND (GP EVENT_DT <= WALES END_DATE)
 DELETE
FROM
	SAILW1429V.LB_GPCARER_STEP4_SWANSEA
WHERE
	(EVENT_DT - 1 YEAR < WELSH_START_DT)
	OR (EVENT_DT > WELSH_END_DT);


-- STEP 5
 CREATE TABLE SAILW1429V.LB_GPCARER_STEP5_SWANSEA (ALF_PE BIGINT,
LSOA_START_DATE DATE,
LSOA_END_DATE DATE,
LSOA2011_CD VARCHAR(10),
WIMD_2019_QUINTILE INTEGER,
LA_NAME VARCHAR(100),
RUC11 VARCHAR(47),
SEX INTEGER,
WOB DATE,
EVENT_DT DATE,
DEATH_DT DATE,
AGE INTEGER,
WELSH_START_DT DATE,
WELSH_END_DT DATE,
WELSH_ADDRESS INTEGER);
-- 12. Link to WLGP SAIL practices
 INSERT
	INTO
	SAILW1429V.LB_GPCARER_STEP5_SWANSEA
SELECT
	A.*
FROM
	SAILW1429V.LB_GPCARER_STEP4_SWANSEA A
LEFT JOIN SAILW1429V.LB_SAIL_GP_REG_LOOKUP S ON
	A.ALF_PE = S.ALF_PE
	-- 13. Drop those not registered with a SAIL GP for 1 year prior to EVENT_DT
	WHERE (A.EVENT_DT - 1 YEAR >= S.START_DATE)
	AND (A.EVENT_DT <= S.END_DATE);


-- 14. Group by ALF, order by event date, add row number to indicate first event when multiple
 ALTER TABLE SAILW1429V.LB_GPCARER_STEP5_SWANSEA ADD COLUMN ROW_NUM INTEGER;

UPDATE
	SAILW1429V.LB_GPCARER_STEP5_SWANSEA
SET
	ROW_NUM = ROW_NUMBER() OVER (PARTITION BY ALF_PE
ORDER BY
	ALF_PE,
	EVENT_DT);

--15. Remove all but first event_dt (where row number != 1)
 DELETE
FROM
	SAILW1429V.LB_GPCARER_STEP5_SWANSEA
WHERE
	ROW_NUM != 1;


-- FINAL TABLE
-- 16. Create final table
 CREATE TABLE SAILW1429V.LB_GPCARER_SWANSEA LIKE SAILW1429V.LB_GPCARER_STEP5_SWANSEA;

INSERT
	INTO
	SAILW1429V.LB_GPCARER_SWANSEA
SELECT
	*
FROM
	SAILW1429V.LB_GPCARER_STEP5_SWANSEA;


-- Check row count
 SELECT
	COUNT(*)
FROM
	SAILW1429V.LB_GPCARER_SWANSEA;


-- Check person count
 SELECT
	COUNT(UNIQUE(ALF_PE))
FROM
	SAILW1429V.LB_GPCARER_SWANSEA;

-- There is now a row per person with their earliest event date (index date)

-- 17. DROP interim tables
 DROP TABLE SAILW1429V.LB_GPCARER_STEP1_SWANSEA;

DROP TABLE SAILW1429V.LB_GPCARER_STEP2_SWANSEA;

DROP TABLE SAILW1429V.LB_GPCARER_STEP3_SWANSEA;

DROP TABLE SAILW1429V.LB_GPCARER_STEP4_SWANSEA;

DROP TABLE SAILW1429V.LB_GPCARER_STEP5_SWANSEA;
