  -- overlap list for Denbighsire
DROP TABLE SAILW1429V.PEJE_OVERLAP_GP_LA_DENBIGHSHIRE_STEP1;

CREATE TABLE SAILW1429V.PEJE_OVERLAP_GP_LA_DENBIGHSHIRE_STEP1
(
Main_ALF_PE BIGINT,
GP_ALF_PE BIGINT,
GP_IDENTIFIED_DATE DATE,
LA_ALF_PE BIGINT,
LA_IDENTIFIED_DATE DATE,
FIRST_IDENTIFIED_BY VARCHAR(3),
FIRST_IDENTIFIED_DATE DATE);

INSERT INTO SAILW1429V.PEJE_OVERLAP_GP_LA_DENBIGHSHIRE_STEP1
SELECT 
CASE 
WHEN gp.EVENT_DT < la.REFERRAL_DATE OR (la.REFERRAL_DATE IS NULL AND gp.EVENT_DT IS NOT NULL)  THEN gp.ALF_PE
WHEN gp.EVENT_DT > la.REFERRAL_DATE OR (la.REFERRAL_DATE IS NOT NULL AND gp.EVENT_DT IS NULL) THEN la.ALF_PE
WHEN gp.EVENT_DT = la.REFERRAL_DATE AND (la.REFERRAL_DATE IS NOT NULL AND gp.EVENT_DT IS NOT NULL) THEN gp.ALF_PE
ELSE NULL
END AS Main_ALF_PE
, gp.ALF_PE AS gp_ALF
, gp.EVENT_DT AS GP_Identified_DT
, la.ALF_PE AS la_ALF
, la.REFERRAL_DATE AS la_REFERRAL_DATE_DT 
-- a. Create first_identified_by flag from LA and GP tables by comparing EVENT_DT and REFERRAL_DATE values
, CASE 
WHEN gp.EVENT_DT < la.REFERRAL_DATE OR (la.REFERRAL_DATE IS NULL AND gp.EVENT_DT IS NOT NULL)  THEN 'GP'
WHEN gp.EVENT_DT > la.REFERRAL_DATE OR (la.REFERRAL_DATE IS NOT NULL AND gp.EVENT_DT IS NULL) THEN 'LA'
WHEN gp.EVENT_DT = la.REFERRAL_DATE AND (la.REFERRAL_DATE IS NOT NULL AND gp.EVENT_DT IS NOT NULL) THEN 'EQ'
ELSE NULL
END AS First_Identified_By
--  b. Select first identified date
, CASE 
WHEN gp.EVENT_DT < la.REFERRAL_DATE OR (la.REFERRAL_DATE IS NULL AND gp.EVENT_DT IS NOT NULL)  THEN gp.EVENT_DT 
WHEN gp.EVENT_DT > la.REFERRAL_DATE OR (la.REFERRAL_DATE IS NOT NULL AND gp.EVENT_DT IS NULL) THEN la.REFERRAL_DATE 
WHEN gp.EVENT_DT = la.REFERRAL_DATE AND (la.REFERRAL_DATE IS NOT NULL AND gp.EVENT_DT IS NOT NULL) THEN gp.EVENT_DT 
ELSE NULL
END AS First_Identified_DT
FROM SAILW1429V.LB_GPCARER_DEN gp
FULL OUTER JOIN 
(SELECT ALF_PE, REFERRAL_DATE FROM SAILW1429V.LB_LA_CARER_DEN ) la 
ON gp.ALF_PE = la.ALF_PE
WHERE gp.ALF_PE = la.ALF_PE; 


-- STEP 2. Select required columns from GP unpaid carers
DROP TABLE SAILW1429V.PEJE_OVERLAP_GP_LA_DENBIGHSHIRE_STEP2;
-- get demographic information of those first identified in GP dataset
CREATE TABLE SAILW1429V.PEJE_OVERLAP_GP_LA_DENBIGHSHIRE_STEP2
(
ALF_PE BIGINT
, SEX INTEGER
, AGE INTEGER
, AGE_STUDYSTART INTEGER
, WOB DATE
, REFERRAL_DATE DATE
, DEATH_DT DATE
, WIMD INTEGER
, RUC11CD VARCHAR(3)
, LA_NAME VARCHAR(100)
, IdentifiedBy VARCHAR(10)
);

INSERT INTO SAILW1429V.PEJE_OVERLAP_GP_LA_DENBIGHSHIRE_STEP2
WITH cte_gp_keycols AS 
(
	-- b. Get baseline characteristics
	SELECT ALF_PE
	, SEX
	, AGE
	, YEARS_BETWEEN('2021-04-01', WOB) AGE_STUDYSTART
	, WOB
	, EVENT_DT AS REFERRAL_DATE
	, DEATH_DT
	, WIMD_2019_QUINTILE AS WIMD
	, RUC11CD, LA_NAME 
	, 'GP' AS IdentifiedBy
	FROM  SAILW1429V.LB_GPCARER_DEN gp
	LEFT JOIN (
	-- c. Add RUC to GP cohort (left join)
		SELECT DISTINCT LSOA11CD, RUC11CD, RUC11
		FROM SAILREFRV.RURAL_URBAN_CLASS_2011_OF_LLSOAREAS_IN_ENG_AND_WAL
		) r	ON gp.LSOA2011_CD = r.LSOA11CD
	
),
cte_gp_carers AS 
(
	-- a. Select those who were first identified in the GP
	SELECT Main_ALF_PE FROM SAILW1429V.PEJE_OVERLAP_GP_LA_DENBIGHSHIRE_STEP1
	WHERE First_Identified_By = 'GP'
)
-- c. Join a and b  (left join)
SELECT g.* FROM cte_gp_carers s
LEFT JOIN (SELECT * FROM cte_gp_keycols )g 
ON s.Main_ALF_PE = g.ALF_PE; 




-- STEP 3. Select required columns from LA unpaid carers
DROP TABLE SAILW1429V.PEJE_OVERLAP_GP_LA_DENBIGHSHIRE_STEP3;
-- get demographic information of those first identified in LA dataset
CREATE TABLE SAILW1429V.PEJE_OVERLAP_GP_LA_DENBIGHSHIRE_STEP3
(
ALF_PE BIGINT
, SEX INTEGER
, AGE INTEGER
, AGE_STUDYSTART INTEGER
, WOB DATE
, REFERRAL_DATE DATE
, DEATH_DT DATE
, WIMD INTEGER
, RUC11CD VARCHAR(3)
, LA_NAME VARCHAR(100)
, IdentifiedBy VARCHAR(10)
);

INSERT INTO SAILW1429V.PEJE_OVERLAP_GP_LA_DENBIGHSHIRE_STEP3
WITH cte_la_keycols AS (
	-- b. Get baseline characteristics
	SELECT ALF_PE
	, SEX
	, AGE
	, YEARS_BETWEEN('2021-04-01', WOB) AGE_STUDYSTART
	, WOB
	, REFERRAL_DATE
	, DOD_CARER AS DEATH_DT
	, WIMD
	, RUC
	, LA_NAME 
	, 'LA' AS IdentifiedBy
	FROM SAILW1429V.LB_LA_CARER_DEN 
),
cte_la_carers AS 
(
	-- a. Select thos who were first identified in the LA
	SELECT Main_ALF_PE FROM SAILW1429V.PEJE_OVERLAP_GP_LA_DENBIGHSHIRE_STEP1
	WHERE First_Identified_By = 'LA'
)
-- c. Join a and b  (left join)
SELECT l.* FROM cte_la_carers s
LEFT JOIN (SELECT * FROM cte_la_keycols ) l
ON s.Main_ALF_PE = l.ALF_PE; 




-- STEP 4. Union key columns from Steps 2 AND 3 
DROP TABLE SAILW1429V.PEJE_OVERLAP_GP_LA_DEN;

CREATE TABLE SAILW1429V.PEJE_OVERLAP_GP_LA_DEN
(
ALF_PE BIGINT
, SEX INTEGER
, AGE INTEGER
, AGE_STUDYSTART INTEGER
, WOB DATE
, REFERRAL_DATE DATE
, DEATH_DT DATE
, WIMD INTEGER
, RUC11CD VARCHAR(3)
, LA_NAME VARCHAR(100)
, IdentifiedBy VARCHAR(10)
, FIRST_IDENTIFIED_DATE DATE
);

INSERT INTO SAILW1429V.PEJE_OVERLAP_GP_LA_DEN
-- - join with first identified date
SELECT u.*, s1.FIRST_IDENTIFIED_DATE FROM SAILW1429V.PEJE_OVERLAP_GP_LA_DENBIGHSHIRE_STEP1 s1
LEFT JOIN (
	-- - Union GP and LA key columns 
	SELECT * FROM SAILW1429V.PEJE_OVERLAP_GP_LA_DENBIGHSHIRE_STEP2
	UNION ALL
	SELECT * FROM SAILW1429V.PEJE_OVERLAP_GP_LA_DENBIGHSHIRE_STEP3
) u 
ON s1.Main_ALF_PE = u.ALF_PE; 

-- check that one row per ALF
SELECT count(DISTINCT ALF_PE) FROM SAILW1429V.PEJE_OVERLAP_GP_LA_DEN; 



-- DELETE INTERIM TABLES
DROP TABLE SAILW1429V.PEJE_OVERLAP_GP_LA_DENBIGHSHIRE_STEP1;
DROP TABLE SAILW1429V.PEJE_OVERLAP_GP_LA_DENBIGHSHIRE_STEP2;
DROP TABLE SAILW1429V.PEJE_OVERLAP_GP_LA_DENBIGHSHIRE_STEP3;


